//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgsv_buildmod.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\MGS\\MGSVTOOLS\\GzsTool\\GzsTool.exe")]
        public string gzsToolPath {
            get {
                return ((string)(this["gzsToolPath"]));
            }
            set {
                this["gzsToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\MGS\\MGSVTOOLS\\FoxEngine.TranslationTool.v0.2.4\\LangTool.exe")]
        public string langToolPath {
            get {
                return ((string)(this["langToolPath"]));
            }
            set {
                this["langToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\MGS\\MGSVTOOLS\\FoxTool\\FoxTool.exe")]
        public string foxToolPath {
            get {
                return ((string)(this["foxToolPath"]));
            }
            set {
                this["foxToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Projects\\MGS\\MGSVTOOLS\\FoxEngine.TranslationTool.v0.2.4\\SubpTool.exe")]
        public string subpToolPath {
            get {
                return ((string)(this["subpToolPath"]));
            }
            set {
                this["subpToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GitHub\\LbaTool\\LbaTool\\bin\\Debug\\LbaTool.exe")]
        public string lbaToolPath {
            get {
                return ((string)(this["lbaToolPath"]));
            }
            set {
                this["lbaToolPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GitHub\\SnakeBite\\makebite\\bin\\Debug\\makebite.exe")]
        public string makeBitePath {
            get {
                return ((string)(this["makeBitePath"]));
            }
            set {
                this["makeBitePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\GitHub\\SnakeBite\\snakebite\\bin\\Debug\\snakebite.exe")]
        public string snakeBitePath {
            get {
                return ((string)(this["snakeBitePath"]));
            }
            set {
                this["snakeBitePath"] = value;
            }
        }
    }
}
